### ISSUE TITLE
Julia 1.0 support

### ISSUE THREAD

**Issue by gabrielgellner** [rdeits/NNLS.jl#13]
I have made the changes to support julia 1.0 (save for how to add LinearAlgebra to the dependencies, which I will figure out). Would this be of interest?

**Comment by tkoolen** [comment]
Of course! Please open a PR. Thanks!

**Comment by gabrielgellner** [comment]
Okay PR made. This will remove likely not work with 0.6, if that is a stopper I can see if I can learn how to us compat etc.
