### ISSUE TITLE
Cannot install NNLS.jl package with Julia 1.4.1

### ISSUE THREAD

**Issue by oniehuis** [rdeits/NNLS.jl#17]
I am having trouble with installing the package with the latest version of Julia (1.4.1):

add https://github.com/rdeits/NNLS.jl
   Updating git-repo `https://github.com/rdeits/NNLS.jl`
ERROR: could not find project file in package at https://github.com/rdeits/NNLS.jl

It would be great if a project file could be added to ease the installation of the package with the recent version of Julia.

**Comment by caseykneale** [comment]
I'll second this - I'd love to use this package for a project

**Comment by blegat** [comment]
Try
```
] add https://github.com/blegat/NNLS.jl#master
```

**Comment by oniehuis** [comment]
Installation worked fine with Julia 1.5.3. Thanks a lot!

**Comment by caseykneale** [comment]
Awesome thank you!
